### ISSUE TITLE
Cannot read properties of undefined (reading 'send')

### ISSUE THREAD

**Issue by KittPhi** [Vonage/vonage-node-code-snippets#109]
Hi Team, unable to [send-sms](https://github.com/Vonage/vonage-node-code-snippets/blob/master/messages/send-sms.js). Did a clean `git clone` of this repo, wondering if the [server-sdk version](https://github.com/Vonage/vonage-node-code-snippets/blob/ad5595f842b7c7bba7a172d162d171f13dd50370/package.json#L27) in the `package.json` is the correct version to work with the node snippet.

**Comment by dragonmantank** [comment]
[The `package-lock.json` is set to pull down `@vonage/server-sdk@2.11.1`](https://github.com/Vonage/vonage-node-code-snippets/blob/ad5595f842b7c7bba7a172d162d171f13dd50370/package-lock.json#L19), which is the current version and has the new `messages` namespace.

Can you check which version of the package you have installed? `npm list @vonage/server-sdk` should return something similar to:

```console
± |master ✓| → npm list @vonage/server-sdk
vonage-node-code-snippets@0.1.0 /home/ctankersley/Projects/vonage/node/vonage-node-code-snippets
└── @vonage/server-sdk@2.11.1
```

**Comment by KittPhi** [comment]
So it should download that version even if the `package.json` is showing `"@vonage/server-sdk": "^2.10.0"`?
```js
➜  vonage-node-code-snippets git:(master) ✗ npm list @vonage/server-sdk
vonage-node-code-snippets@0.1.0 /Users/kittphi/Desktop/Repos/vonage-node-code-snippets
└── @vonage/server-sdk@2.10.0

➜  vonage-node-code-snippets git:(master) ✗ 
```

**Comment by dragonmantank** [comment]
Interesting, as the [`package.json` file is set to `^2.11.0` now in `master`](https://github.com/Vonage/vonage-node-code-snippets/blob/ad5595f842b7c7bba7a172d162d171f13dd50370/package.json#L27).

Can you try and update the repository with `git pull --rebase origin master` to make sure it's pulling in the remote changes to your local `master` branch?

**Comment by KittPhi** [comment]
I ran the command you suggested `git pull --rebase origin master` and it pulled the correct version.

```js
➜  vonage-node-code-snippets git:(master) npm list @vonage/server-sdk     
vonage-node-code-snippets@0.1.0 /Users/kittphi/Desktop/Repos/vonage-node-code-snippets
└── @vonage/server-sdk@2.11.1
➜  vonage-node-code-snippets git:(master) node ./messages/send-sms.js     
{
  body: {
    title: 'Invalid params',
``` 

Looks like the provided [.env-example](https://github.com/Vonage/vonage-node-code-snippets/blob/ad5595f842b7c7bba7a172d162d171f13dd50370/.env-example#L5) will need to be updated to the correct [process.env.TO_NUMBER](https://github.com/Vonage/vonage-node-code-snippets/blob/ad5595f842b7c7bba7a172d162d171f13dd50370/messages/send-mms.js#L8) and FROM_NUMBER. Thanks for helping out with that 🍻.
