### ISSUE TITLE
sendSms bad typing: Expected 5 arguments, but got 4.

### ISSUE THREAD

**Issue by AnthonyLzq** [Vonage/vonage-node-code-snippets#113]
The type for the function `sendSms` is wrong, in the example you are using 4 arguments, but in its type declaration 5 arguments are needed.

## Expected Behavior
Calling the `sendSms` function and passing arguments like in the example should work.

## Current Behavior
There is an error when I try to use the `sendSms` function. I have the following SS:

![image](https://user-images.githubusercontent.com/43073718/181409498-c684a7b6-bed0-4c0f-943c-e14f743dfe23.png)

![image](https://user-images.githubusercontent.com/43073718/181409585-db5d5bd0-92f0-463f-b302-d5c6f3e66392.png)

## Possible Solution

Update the docs to provide a correct example or update the type of the function.

## Steps to Reproduce

1. Try to run [this](https://github.com/Vonage/vonage-node-code-snippets/blob/master/sms/send.js) using TypeScript

## Context (Environment)

I'm trying to test your API following the basic example for sending an sms. I'm currently using:

- Node.js: v16.16.0
- TypeScript: v4.7.4
- @vonage/server-sdk: v2.11.2

**Comment by dragonmantank** [comment]
Previous to v3 our typescript definitions were community maintained, but v3 now ships with proper typescript definitions.
