### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by GadeBao** [Vonage/vonage-node-code-snippets#120]
## Expected Behavior
node sms/send.js will run the code

## Current Behavior
node sms/send.js got a build error

## Possible Solution
Missing library code?

## Steps to Reproduce
1. git clone https://github.com/GadeBao/vonage-node-code-snippets.git
2. cd vonage-node-code-snippets.git
3. npm install --save @vonage/server-sdk
4. node sms/send.js

## Context (Environment)

build error

## Detailed Description

node:internal/modules/cjs/loader:410
      throw err;
      ^

Error: Cannot find module '/home/billy_bao/Vonage/vonage-node-code-snippets/node_modules/@vonage/vetch/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:402:19)
    at Module._findPath (node:internal/modules/cjs/loader:644:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1012:27)
    at Module._load (node:internal/modules/cjs/loader:872:27)
    at Module.require (node:internal/modules/cjs/loader:1092:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/billy_bao/Vonage/vonage-node-code-snippets/node_modules/@vonage/server-client/dist/client.js:14:17)
    at Module._compile (node:internal/modules/cjs/loader:1205:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1259:10)
    at Module.load (node:internal/modules/cjs/loader:1068:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/billy_bao/Vonage/vonage-node-code-snippets/node_modules/@vonage/vetch/package.json',
  requestPath: '@vonage/vetch'

## Possible Implementation
<!--- Not obligatory, but suggest an idea for implementing addit

**Comment by GadeBao** [comment]
Hi Team,

I also wondering if "sendSms" is exported via {Vonage} module.

`
const { Vonage } = require('@vonage/server-sdk')
vonage.message.sendSms(from, to, text, opts, (err, responseData) => {
    if (err) {
        console.log(err);
    } else {
        if(responseData.messages[0]['status'] === "0") {
            console.log("Message sent successfully.");
        } else {
            console.log(`Message failed with error: ${responseData.messages[0]['error-text']}`);
        }
    }
})`

**Comment by dragonmantank** [comment]
Hello @GadeBao !

The build issue should be fixed. We had a bad compile of @vonage/jwt that went out that messed up the main package for a bit, but that has been resolved as of 3.0.8. If you update to the latest version of @vonage/server-sdk you should be good. Let me know if it gives you any more build problems.

As for the code snippet, you've caught us in the middle of a new release, so some of the code snippets are lagging behind (#119 is housing the last few changes). The SDK has moved from callbacks to promises, and many methods have changed. For the SMS, this includes a change from `vonage.message` to `vonage.sms`, to better differentiate the SMS-only API and our multi-channel Messages API. Some more information can be found at https://github.com/Vonage/vonage-node-sdk/blob/3.x/packages/sms/v2_TO_v3_MIGRATION_GUIDE.md

For the snippet above, take a look at https://github.com/Vonage/vonage-node-code-snippets/blob/master/sms/send.js for the correct syntax. If you are sending a signed message, the only difference is supplying the signature along with your credentials, the interface for sending an SMS is the same for signed and non-signed messages.

I'm closing this ticket for now, but feel free to re-open if you have any more issues, or feel free to create a new ticket if you run into anything else.

Good luck!
