### ISSUE TITLE
verify.start not fund

### ISSUE THREAD

**Issue by GadeBao** [Vonage/vonage-node-code-snippets#121]
Hi Team,

This code seems does not work - it returns `**undefined**` error indicating that the method signature is unmatching.

`vonage.verify.start({
  number: RECIPIENT_NUMBER,
  senderId: BRAND_NAME
})`

**Comment by biligeny** [comment]
Any update on this, please?

**Comment by dragonmantank** [comment]
'vonage.verify.start()' is a new method in v3. Can you let us know what version of the SDK you currently have installed?

**Comment by biligeny** [comment]
Hi,

I am using this version.

"dependencies": {
    "@vonage/server-sdk": "^3.0.9",
    "express": "^4.18.2",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "nodemon": "^2.0.20"
  }

<img width="983" alt="スクリーンショット 2022-11-26 午前10 52 05" src="https://user-images.githubusercontent.com/1286146/204067906-cb159759-5e03-4614-8552-4c421b9cbfdf.png">

**Comment by biligeny** [comment]
Hi [dragonmantank](https://github.com/dragonmantank)

I also cloned the repository and ran following but got the same error.

- setup .env 
- install dotenv
- npm install && npm update
- node verify/request.js

Thanks

**Comment by dragonmantank** [comment]
I just corrected an argument typo in the code snippet, can you re-pull this repository and try again? If you ran the snippet it should have just printed 'undefined' and not sent the code, this fix corrects that.

that was a different issue than what you are experiencing though. On your express install, and your code snippet install, can you see if there is anything in `node_modules/@vonage/verify/dist` ? Though if all that code is missing you shouldn't even be able to create a Vonage object, as Verify is a required component. 

Can you also verify in your express app that the `context` object has a proper Vonage object? That looks like custom code, so if that isn't set properly `.verify` won't be available either.

**Comment by GadeBao** [comment]
Hi,

The request.js is working now after you corrected the signature.

The context is just a wrapper of Vonage as a singleton, and it works as check.js is not issue.

Apart from it and regarding dist, please find below.
![image](https://user-images.githubusercontent.com/101109076/204176787-ffdee6c3-3fc8-4504-8e85-0b62a3280dc1.png)

I wonder if SDK V.3 relies on node version like v.16 or v.18?

Thanks,
