### ISSUE TITLE
Rooms SDK auth credentials 401

### ISSUE THREAD

**Issue by JefferyHus** [Vonage/vonage-node-code-snippets#140]
## Expected Behavior

The Rooms SDK to request and return proper response.

## Current Behavior

It throws unauthorized error.

## Possible Solution

Allow the user to generate their own JWT token instead of using your `auth` library and hook it into the rooms sdk;

## Steps to Reproduce

1. Initiate the auth sdk with the proper options
```typescript
    const privateKeyPath = path.join(
      process.cwd(),
      String(process.env.VONAGE_PRIVATE_KEY),
    );

    const privateKeyContent = fs.readFileSync(privateKeyPath);

    // initialize the Vonage Auth
    this.auth = new Auth({
      privateKey: privateKeyContent,
      applicationId: process.env.VONAGE_APPICATION_ID,
    });
```

2. Execute the room sdk
```typescript
    // initialize the Vonage Meetings
    this.meetings = new Meetings(this.auth);

    // create a room
    const room = await this.meetings.createRoom({
      displayName: roomName,
      type: roomtype,
      joinApprovalLevel: JoinType.EXPLICT_APPROVAL,
      availableFeatures: features,
    });

    return room;
```

## Context (Environment)

I am trying to create an instant room, doing so using your own existing SDKs throws a 401 status all the time, so it does not recognize the credentials properly. I have tried to fill in all the auth properties with api keyss..etc but same issue.

To my surprise when I try to do the same thing using a custom http request with fetch or axios or just http class, it works as expected and I get a 200 with the room details.

## Possible Implementation
<!--- Not obligatory, but suggest an idea for implementing addit

**Comment by manchuck** [comment]
Apologies for the issue; however, the meeting's API has been deprecated. Please choose a different solution that fits your needs.
