### ISSUE TITLE
applications code snippet: outdated script

### ISSUE THREAD

**Issue by porcherface** [Vonage/vonage-node-code-snippets#153]
the updateApplication method does not read the applicationId field, leading to undefined webhook when making the api call

## Expected Behavior
return a merged application

## Current Behavior
returns error 404 due to missing id in url

## Possible Solution
 from a quick inspection of  the sdk code the module expects an "id" field rather than "applicationId"

## Steps to Reproduce
run this with any .env provided by vonage :
https://github.com/Vonage/vonage-node-code-snippets/blob/master/applications/update-application.js

## Possible Implementation
just namefix

**Comment by manchuck** [comment]
The snippet has been updated
