### ISSUE TITLE
vonage.channel missing when attempting to send whatsapp message

### ISSUE THREAD

**Issue by toolkit** [Vonage/vonage-node-code-snippets#98]
I am attempting to use the whatsapp send-template example.
However, when I try to invoke vonage.channel.send, I get:
TypeError: Cannot read property 'send' of undefined
That is, the channel attribute appears to be missing. 
Is there some way to determine why this attribute cannot be found?

**Comment by toolkit** [comment]
Must be something specific on my side, will investigate further.

**Comment by toolkit** [comment]
$ npm show @vonage/server-sdk version 
2.10.2

**Comment by laurentlp** [comment]
@toolkit 

```bash
$ npm install @vonage/server-sdk@beta
```
